name: Build APK

on: [push]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
      
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Install Capacitor
      run: |
        npm install -g @capacitor/cli
        npm install @capacitor/core @capacitor/android
        
    - name: Initialize Capacitor
      run: |
        npx cap init --web-dir ./ --package-id com.workcalendar.app --app-name "Work Calendar" -y
        
    - name: Build Android Project
      run: |
        npx cap add android
        npx cap copy
        cd android
        chmod +x ./gradlew
        ./gradlew assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: work-calendar-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
